# Generated by Django 3.2.4 on 2021-07-06 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notif', '0002_item_date_posted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='keywords',
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to='notif.keyword'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='me',
            name='interest',
        ),
        migrations.AddField(
            model_name='me',
            name='interest',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to='notif.keyword'),
            preserve_default=False,
        ),
    ]
