# Generated by Django 3.2.4 on 2021-07-06 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notif', '0003_auto_20210706_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='me',
            name='interest',
        ),
        migrations.AddField(
            model_name='me',
            name='interest',
            field=models.ManyToManyField(to='notif.Keyword'),
        ),
    ]
