# Generated by Django 3.2.4 on 2021-07-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notif', '0004_auto_20210706_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='me',
            name='interest',
            field=models.ManyToManyField(blank=True, to='notif.Keyword'),
        ),
    ]
